select
	cdu.nm_usuario,
	cdu.dt_nascimento
	
	
	
from
	dispensacao_medicamento dm
	join usuario_cadsus cdu on cdu.cd_usu_cadsus = dm.cd_usu_cadsus_destino
	
	 
	
where
	dm.dt_dispensacao >= '2021-01-01'::date and
	/*rti.nm_produto in  ('ANLODIPINO, BESILATO 5 MG',
						'ANLODIPINO, BESILATO 10 MG',
						'AMIODARONA 200 MG',
						'ATENOLOL 50 MG',
						'CARVEDILOL 25MG',
						'CARVEDILOL 6,25 MG', 
						'CAPTOPRIL 12,5 MG',
						'DIGOXINA 0,25 MG',
						'ENALAPRIL, MALEATO 5MG',
						'ENALAPRIL, MALEATO 20 MG',
						'ENALAPRIL, MALEATO  10 MG', 
						'ESPIRONOLACTONA 25 MG',
						'FUROSEMIDA 40 MG',
						'HIDROCLOROTIAZIDA 25 MG',
						'ISOSSORBIDA, DINITRATO 5 MG SUBLINGUAL',
						'ISOSSORBIDA, MONONITRATO 20 MG',
						'LOSARTANA POTÁSSICA 50 MG',
						'METILDOPA 250 MG',
						'PROPRANOLOL, CLORIDRATO 40 MG' 
						'SINVASTATINA 40 MG',
						'SINVASTATINA 20 MG',
						'VERAPAMIL, CLORIDRATO 80 MG', 
						'GLIBENCLAMIDA 5 MG',
						'INSULINA HUMANA NPH 100 UI/ML- CANETA',
						'INSULINA HUMANA REGULAR 100 UI/ML – CANETA', 
						'INSULINA NPH  U100',
						'INSULINA REGULAR  U100',
						'INSULINA REGULAR HUMANA 100 UI/ML'
						'INSULINA NPH HUMANA 100 UI/ML',
						'METFORMINA, CLORIDRATO 850 MG',
						'ACIDO ACETIL SALICILICO 100 MG'
						'CLOPIDOGREL 75 MG',
						'AGULHA PARA CANETA DE INSULINA',
						'AGULHA BD P/ CANETA DE INSULINA 4 MM',
						'AGULHA BD P/ CANETA DE INSULINA 5 MM',
						'AGULHA BD P/ CANETA DE INSULINA 8 MM') */
 ;
	
	